### ISSUE TITLE
[Bug]: Missing Method UseMauiCommunityToolKit()

### ISSUE THREAD

**Issue by mjphillips1981** [shinyorg/templates#1]
### Steps To Reproduce

1) Create new project using v1.0.0-ALPHA-0020
2) Build and run new project on Android.

### Issue (ie.Compiler Error)

System.MissingMethodException: 'Method not found: Microsoft.Maui.Hosting.MauiAppBuilder CommunityToolkit.Maui.AppBuilderExtensions.UseMauiCommunityToolkit(Microsoft.Maui.Hosting.MauiAppBuilder)'
![Shiny Selections](https://user-images.githubusercontent.com/2092513/198077821-7b8ccbf0-52e6-48bb-8eff-15bfad12d459.png)

![shiny exception](https://user-images.githubusercontent.com/2092513/198078361-445f6935-a619-4ebb-a88c-1cd11847829c.png)

**Comment by mjphillips1981** [comment]
Hey Allan,
I am still getting this error.  I ran dotnet new --update-apply saw that v21 was installed.  Created a brand-new project with the same selections as above.  I am on VS2022 Preview 5.0 if that means anything for ya.

Thanks, Mike

![image](https://user-images.githubusercontent.com/2092513/198270252-5c7328b7-64b1-44f1-b093-4f6b5d6fac13.png)

**Comment by aritchie** [comment]
This is a binary incompatibility with Shiny Framework and MAUI community toolkit at the moment.  The fix will be out today
