### ISSUE TITLE
[Bug]: Missing <UseMaui>true</UseMaui>

### ISSUE THREAD

**Issue by RobGibbens** [shinyorg/templates#10]
### Steps To Reproduce

1. Create a new Shiny MAUI Application
2. On Visual Studio 2022, "Windows Machine" is the only debug option. On VS Code, it can't debug and run.
3. Add <UseMaui>true</UseMaui> to the csproj and everything works as expected.

### Issue (ie.Compiler Error)

Can not debug app.

**Comment by aritchie** [comment]
Thanks for the bug report.  Not sure why I took this out...?

Fix is already live on nuget
