### ISSUE TITLE
[Bug]: New Project with AzureNotificationHub creates wrong Code

### ISSUE THREAD

**Issue by enny1170** [shinyorg/templates#5]
### Steps To Reproduce

1. Update your Template to use 3.0 beta
2. create a new Project and select services from screenshot
3. try to build

![Bildschirmfoto 2023-04-19 um 10 36 21](https://user-images.githubusercontent.com/18047568/233019962-835d28f2-c6da-4120-8dc0-eeb15d421ac4.png)

### Issue (ie.Compiler Error)

you get a compiling Error like this
shinyTemplateTest/MauiProgram.cs(49,11,49,83): error CS7036: Missing Argument for Parameter "hubName" on "ServiceCollectionExtensions.AddPushAzureNotificationHubs<TPushDelegate>(IServiceCollection, string, string)".

the code generated in MauiProgram.cs is

s.AddPushAzureNotificationHubs<shinyTemplateTest.Delegates.MyPushDelegate>(new (
            builder.Configuration["AzureNotificationHubs:ListenerConnectionString"], 
            builder.Configuration["AzureNotificationHubs:HubName"]
        ));
change it to
s.AddPushAzureNotificationHubs<shinyTemplateTest.Delegates.MyPushDelegate>(
            builder.Configuration["AzureNotificationHubs:ListenerConnectionString"], 
            builder.Configuration["AzureNotificationHubs:HubName"]
        );

will fix them

**Comment by aritchie** [comment]
Thank you for the report.  This has been resolved with beta2 of the template
