### ISSUE TITLE
[Bug]: New Generated Project does not run on MacCatalyst

### ISSUE THREAD

**Issue by enny1170** [shinyorg/templates#6]
### Steps To Reproduce

1. Update Templates to use shiny 3.0-beta
2. create a new Shiny Maui Project from Template
3. Select Services like Screenshot
4. Build
5. Start Debug On My Mac (MacCatalyst) 
![Bildschirmfoto 2023-04-19 um 10 36 21](https://user-images.githubusercontent.com/18047568/233023651-86684db0-de5b-4ae3-a656-56f581ed15d5.png)

### Issue (ie.Compiler Error)

The Project builds successfully and start the Debugger
The Debugger will fail with Message in Screenshot
![Bildschirmfoto 2023-04-19 um 10 58 44](https://user-images.githubusercontent.com/18047568/233024209-2994614b-d901-443a-aac4-f02c1e866fa2.png)

Try Debugging on IOS Simulator will work

**Comment by enny1170** [comment]
After some Try I find a better Error Description:

The application cannot be opened for an unexpected reason, error=Error Domain=RBSRequestErrorDomain Code=5 "Launch failed." UserInfo={NSLocalizedFailureReason=Launch failed., NSUnderlyingError=0x1301065a0 {Error Domain=NSPOSIXErrorDomain Code=153 "Unknown error: 153" UserInfo={NSLocalizedDescription=Launchd job spawn failed}}}

maybe it will be helpful to identify and solve the problem.

**Comment by aritchie** [comment]
This isn't an issue with the template.  You need to ensure you have a proper provisioning profile setup for maccatalyst.  iOS will fail to deploy if the provisioning profile with push can't be found, catalyst will just crash.  You can prove this by removing the entitlements.plist for your code or manually setting the proper profile in the build settings.  Only so much I can do from the template perspective.
