### ISSUE TITLE
[Bug]: 'TestOptions' could not be found (.\MauiProgram.cs:7)

### ISSUE THREAD

**Issue by darkbluea** [shinyorg/templates#7]
### Steps To Reproduce

1. Create new project with template XUnitDeviceRunner MAUITests (Shiny .NET)
- Framework: .NET 7.0 (Standard Term Support)
2. Disable frameworks - net7.0-android - and - net7.0-maccatalyst -
3. Delete now useless Platforms directories (Android, MacCatalyst and Tizen)
4. Build

### Issue (ie.Compiler Error)

Severity	Code	Description	Project	Path	File	Line	Suppression State
Error	CS0246	The type or namespace name 'TestOptions' could not be found (are you missing a using directive or an assembly reference?)	NewTests (net7.0-windows10.0.19041.0)	C:\DassaultDUOS\fsv3-framework\FSDA\NewTests	C:\DassaultDUOS\fsv3-framework\FSDA\NewTests\MauiProgram.cs	7	Active

**Comment by darkbluea** [comment]
The file MauiProgram.cs only need `using Xunit.Runners.Maui;` at the start.

**Comment by aritchie** [comment]
Thanks for reporting this.  It will be fixed in the next release
